apps/common/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import direct_to_template
from django.conf import settings

urlpatterns = patterns('common.views',
    url(r'^about/$', direct_to_template, {'template': 'about.html'}, 'about_view'),
    url(r'^license/$', 'license_view', (), 'license_view'),
    url(r'^password/change/done/$', 'password_change_done', (), name='password_change_done'),
    url(r'^object/multiple/action/$', 'multi_object_action_view', (), name='multi_object_action_view'),

    url(r'^user/$', 'current_user_details', (), 'current_user_details'),
    url(r'^user/edit/$', 'current_user_edit', (), 'current_user_edit'),

    url(r'^login/$', 'login_view', (), name='login_view'),
    url(r'^password/change/$', 'password_change_view', (), name='password_change_view'),
)

urlpatterns += patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout_view'),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', {'email_template_name': 'password_reset_email.html', 'template_name': 'password_reset_form.html', 'post_reset_redirect': '/password/reset/done'}, name='password_reset_view'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'password_reset_confirm.html', 'post_reset_redirect': '/password/reset/complete/'}, name='password_reset_confirm_view'),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'password_reset_complete.html'}, name='password_reset_complete_view'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'password_reset_done.html'}, name='password_reset_done_view'),

    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '%s%s' % (settings.STATIC_URL, 'images/favicon.ico')}),
)

urlpatterns += patterns('',
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),
)

apps/main/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'home', (), 'home'),
)

mayan/apps/ocr/urls.py
from django.conf.urls import url

from .api_views import (
    APIDocumentTypeOCRSettingsView, APIDocumentOCRSubmitView,
    APIDocumentVersionOCRContentView, APIDocumentVersionPageOCRContentView
)
from .views import (
    DocumentVersionOCRContentDeleteView, DocumentVersionOCRContentView,
    DocumentVersionOCRDownloadView,
    DocumentVersionOCRErrorsListView, DocumentVersionPageOCRContentView,
    DocumentVersionOCRSubmitView,
    DocumentTypeSettingsEditView, DocumentTypeSubmitView, EntryListView
)

urlpatterns_document_types = [
    url(
        regex=r'^document_types/submit/$', name='document_type_submit',
        view=DocumentTypeSubmitView.as_view()
    ),
    url(
        regex=r'^document_types/(?P<document_type_id>\d+)/ocr/settings/$',
        name='document_type_ocr_settings',
        view=DocumentTypeSettingsEditView.as_view()
    )
]

urlpatterns_document_versions = [
    url(
        regex=r'^documents/versions/(?P<document_version_id>\d+)/content/$',
        name='document_version_ocr_content_view',
        view=DocumentVersionOCRContentView.as_view()
    ),
    url(
        regex=r'^documents/versions/(?P<document_version_id>\d+)/content/delete/$',
        name='document_version_ocr_content_delete',
        view=DocumentVersionOCRContentDeleteView.as_view()
    ),
    url(
        regex=r'^documents/versions/multiple/content/delete/$',
        name='document_version_multiple_ocr_content_delete',
        view=DocumentVersionOCRContentDeleteView.as_view()
    ),
    url(
        regex=r'^documents/versions/(?P<document_version_id>\d+)/ocr/download/$',
        name='document_version_ocr_download',
        view=DocumentVersionOCRDownloadView.as_view()
    ),
    url(
        regex=r'^documents/versions/(?P<document_version_id>\d+)/ocr/errors/$',
        name='document_version_ocr_error_list',
        view=DocumentVersionOCRErrorsListView.as_view()
    ),
    url(
        regex=r'^documents/versions/(?P<document_version_id>\d+)/submit/$',
        name='document_version_ocr_submit',
        view=DocumentVersionOCRSubmitView.as_view()
    ),
    url(
        regex=r'^documents/versions/multiple/submit/$',
        name='document_version_multiple_ocr_submit',
        view=DocumentVersionOCRSubmitView.as_view()
    ),
    url(
        regex=r'^documents/versions/pages/(?P<document_version_page_id>\d+)/content/$',
        name='document_version_page_ocr_content_view',
        view=DocumentVersionPageOCRContentView.as_view()
    ),
    url(regex=r'^logs/$', name='entry_list', view=EntryListView.as_view())
]

urlpatterns = []
urlpatterns.extend(urlpatterns_document_types)
urlpatterns.extend(urlpatterns_document_versions)

api_urls = [
    url(
        regex=r'^document_types/(?P<document_type_id>\d+)/ocr/settings/$',
        name='document-type-ocr-settings-view',
        view=APIDocumentTypeOCRSettingsView.as_view()
    ),
    url(
        regex=r'^documents/(?P<document_id>\d+)/ocr/submit/$',
        name='document-ocr-submit-view',
        view=APIDocumentOCRSubmitView.as_view()
    ),
    url(
        regex=r'^documents/(?P<document_id>\d+)/versions/(?P<document_version_id>\d+)/ocr/submit/$',
        name='document-version-ocr-submit-view',
        view=APIDocumentVersionOCRContentView.as_view()
    ),
    url(
        regex=r'^documents/(?P<document_id>\d+)/versions/(?P<document_version_id>\d+)/pages/(?P<document_version_page_id>\d+)/ocr/$',
        name='document-version-page-ocr-content-view',
        view=APIDocumentVersionPageOCRContentView.as_view()
    ),
]

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('main.urls')),
    (r'^apps/', include('app_registry.urls')),#, namespace='apps')),
    (r'^common/', include('common.urls')),
    (r'^permissions/', include('permissions.urls')),
    (r'^setup/', include('project_setup.urls')),
    (r'^tools/', include('project_tools.urls')),
    (r'^settings/', include('smart_settings.urls')),
    (r'^documents/', include('documents.urls')),
    (r'^folders/', include('folders.urls')),
    (r'^search/', include('dynamic_search.urls')),
    (r'^ocr/', include('ocr.urls')),
    (r'^tags/', include('tags.urls')),
    (r'^comments/', include('document_comments.urls')),
    (r'^user_management/', include('user_management.urls')),
    (r'^metadata/', include('metadata.urls')),
    (r'^linking/', include('linking.urls')),
    (r'^document_indexing/', include('document_indexing.urls')),
    (r'^history/', include('history.urls')),
    (r'^converter/', include('converter.urls')),
    (r'^sources/', include('sources.urls')),
    (r'^acls/', include('acls.urls')),
    #(r'^document_acls/', include('document_acls.urls')),
    (r'^api/', include('rest_api.urls')),
    (r'^gpg/', include('django_gpg.urls')),
    (r'^documents/signatures/', include('document_signatures.urls')),
    #(r'^mailer/', include('mailer.urls')),
    #(r'^workflows/', include('workflows.urls')),
    #(r'^checkouts/', include('checkouts.urls')),
    #(r'^installation/', include('installation.urls')),
    (r'^scheduler/', include('scheduler.urls')),
    (r'^registration/', include('registration.urls')),
    (r'^job_processing/', include('job_processor.urls')),
    (r'^bootstrap/', include('bootstrap.urls')),
    (r'^diagnostics/', include('diagnostics.urls')),
    (r'^maintenance/', include('maintenance.urls')),
    (r'^statistics/', include('statistics.urls')),
    (r'^clustering/', include('clustering.urls')),
    (r'^trash/', include('trash.urls')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)


def handler500(request):
    """
    500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')  # You need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

if settings.DEVELOPMENT:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += patterns('',
            url(r'^rosetta/', include('rosetta.urls'), name='rosetta'),
        )

mayan/apps/common/models.py
import uuid


# Required by migration 0010_auto_20180403_0702.py
def upload_to(instance, filename):
    return 'shared-file-{}'.format(uuid.uuid4().hex)

apps/common/forms.py
from __future__ import absolute_import

import os

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.conf import settings

from .utils import return_attrib
from .widgets import (DetailSelectMultiple, PlainWidget, TextAreaDiv,
    EmailInput)


class DetailForm(forms.ModelForm):
    def __init__(self, extra_fields=None, *args, **kwargs):
        super(DetailForm, self).__init__(*args, **kwargs)
        if extra_fields:
            for extra_field in extra_fields:
                result = return_attrib(self.instance, extra_field['field'])
                label = 'label' in extra_field and extra_field['label'] or None
                #TODO: Add others result types <=> Field types
                if isinstance(result, models.query.QuerySet):
                    self.fields[extra_field['field']] = \
                        forms.ModelMultipleChoiceField(
                            queryset=result, label=label)
                else:
                    self.fields[extra_field['field']] = forms.CharField(
                        label=extra_field['label'],
                        initial=return_attrib(self.instance,
                            extra_field['field'], None),
                            widget=PlainWidget)

        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.SelectMultiple):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text = ''
            elif isinstance(field.widget, forms.widgets.Select):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text = ''

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs.update({'readonly': 'readonly'})


class GenericConfirmForm(forms.Form):
    def __init__(self, *args, **kwargs):
        pass


class GenericAssignRemoveForm(forms.Form):
    def __init__(self, *args, **kwargs):
        left_list_qryset = kwargs.pop('left_list_qryset', None)
        right_list_qryset = kwargs.pop('right_list_qryset', None)
        left_filter = kwargs.pop('left_filter', None)
        super(GenericAssignRemoveForm, self).__init__(*args, **kwargs)
        if left_filter:
            self.fields['left_list'].queryset = left_list_qryset.filter(
                *left_filter)
        else:
            self.fields['left_list'].queryset = left_list_qryset

        self.fields['right_list'].queryset = right_list_qryset

    left_list = forms.ModelMultipleChoiceField(required=False, queryset=None)
    right_list = forms.ModelMultipleChoiceField(required=False, queryset=None)


class FilterForm(forms.Form):
    def __init__(self, list_filters, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        for list_filter in list_filters:
            label = list_filter.get('title', list_filter['name'])
            self.fields[list_filter['name']] = forms.ModelChoiceField(
                queryset=list_filter['queryset'],
                label=label[0].upper() + label[1:], required=False)


class ChoiceForm(forms.Form):
    """
    Form to be used in side by side templates used to add or remove
    items from a many to many field
    """
    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices', [])
        label = kwargs.pop('label', _(u'Selection'))
        super(ChoiceForm, self).__init__(*args, **kwargs)
        self.fields['selection'].choices = choices
        self.fields['selection'].label = label
        self.fields['selection'].widget.attrs.update({'size': 14, 'class': 'choice_form'})

    selection = forms.MultipleChoiceField()


class UserForm_view(DetailForm):
    """
    Form used to display an user's public details
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'is_staff', 'is_superuser', 'last_login', 'date_joined', 'groups')


class UserForm(forms.ModelForm):
    """
    Form used to edit an user's mininal fields by the user himself
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class EmailAuthenticationForm(AuthenticationForm):
    """
    Override the default authentication form to use email address
    authentication
    """
    email = forms.CharField(label=_(u'Email'), max_length=75,
        widget=EmailInput(attrs={'style': 'width: 100%;'})
    )

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(_('Please enter a correct email and password. Note that the password fields is case-sensitive.'))
            elif not self.user_cache.is_active:
                raise forms.ValidationError(_('This account is inactive.'))
        self.check_for_test_cookie()
        return self.cleaned_data

# Remove the inherited username field
EmailAuthenticationForm.base_fields.keyOrder = ['email', 'password']


class FileDisplayForm(forms.Form):
    text = forms.CharField(
        label='',  # _(u'Text'),
        widget=forms.widgets.Textarea(
            attrs={'cols': 40, 'rows': 20, 'readonly': 'readonly'}
        )
    )

    def __init__(self, *args, **kwargs):
        super(FileDisplayForm, self).__init__(*args, **kwargs)
        changelog_path = os.path.join(settings.PROJECT_ROOT, os.sep.join(self.DIRECTORY), self.FILENAME)
        fd = open(changelog_path)
        self.fields['text'].initial = fd.read()
        fd.close()


class LicenseForm(FileDisplayForm):
    FILENAME = u'LICENSE'
    DIRECTORY = [u'docs', u'credits']

mayan/apps/common/forms.py
from mayan.apps.views.forms import FileDisplayForm


class LicenseForm(FileDisplayForm):
    DIRECTORY = ()
    FILENAME = 'LICENSE'

apps/common/templates/generic_assign_remove.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} :: {% blocktrans %}Assign {{ title }} {{ object }}{% endblocktrans %}{% endblock %}


{% block content %}
    <style>
        #id_right_list,#id_left_list { min-width: 28em; min-height: 13em; }
    </style>
    <div class="content">   
    <h2 class="title">{{ title|safe }}</h2>
    
    <form method='POST' action='' id='assign_remove'>{% csrf_token %}
        <input name='action' value='' type='hidden' />
         <table>
            <tbody>
                <tr>
                    <th style='text-align:center;'>{{ left_list_title }}</th><td></td><th style='text-align:center;'>{{ right_list_title }}</th>
                </tr>
                <tr>
                    <td>
                        {{ form.left_list }}{{ form.left_list.errors }}
                    </td>
                    <td>
                        <table>
                            <tbody>
                                <tr>
                                  <td><button class="button" onclick='document.forms["assign_remove"].action.value="assign";document.forms["assign_remove"].submit();'>&gt;</button></td>
                                </tr>
                                <tr>
                                  <td><button class="button" onclick='document.forms["assign_remove"].action.value="remove";document.forms["assign_remove"].submit();'>&lt;</button></td>
                                </tr>
                            </tbody>					
                        </table>
                    </td>
                    <td>{{ form.right_list }}{{ form.right_list.errors }}</td>
                </tr>
                {{ form.media|safe }}			
            </tbody>
        </table>
    </form>
    </div>
{% endblock %}

apps/common/templates/generic_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} :: {% trans "Confirm" %} {{ title }}{% endblock %}

{% block sidebar %}
    {% for subtemplate in subtemplates %}
        {% include subtemplate %}
    {% endfor %}
{% endblock %}

{% block content %}
                
    <div class="content">    
        <h2 class="title">
            {% if delete_view %}      
                {% trans "Confirm delete" %}
            {% else %}
                {% trans "Confirm" %}
            {% endif %}
        </h2>
        <div class="inner">
            <form action="" method="post" class="form login">{% csrf_token %}
                {% if next %}
                    <input name="next" type="hidden" value="{{ next }}" />
                {% endif %}   
                       
                {% if previous %}
                    <input name="previous" type="hidden" value="{{ previous }}" />
                {% endif %}   
                
                <div style="float: left; margin-right: 10px;">
                    {{ form_icon.display_big }}
                    {#<img style="margin-top: 12px;" src="{{ STATIC_URL }}images/icons/{{ form_icon|default:'question.png' }}" alt="{% trans 'form icon' %}" />#}
                </div>                
                <div style="float: left; width: 90%;">
                {% if title %}
                    <h3>{{ title }}</h3>
                {% else %}
                    {% if delete_view %}
                        {% if object_name %}
                            <h3>{% blocktrans %}Are you sure you wish to delete {{ object_name }}: {{ object }}?{% endblocktrans %}</h3>
                        {% else %}
                            <h3>{% blocktrans %}Are you sure you wish to delete: {{ object }}?{% endblocktrans %}</h3>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <h4>{{ message }}</h4>

                <div class="group navform wat-cf">        
                  <button class="button" type="submit">
                    <img src="{{ STATIC_URL }}web_theme_media/images/icons/tick.png" alt="{% trans 'Yes' %}" /> {% trans "Yes" %}
                  </button>
                  {% if previous %}
                  <a href="#header" onclick='{% if previous %}window.location.replace("{{ previous }}");{% else %}history.go(-1);{% endif %}' class="button">
                    <img src="{{ STATIC_URL }}web_theme_media/images/icons/cross.png"  alt="{% trans 'No' %}"/> {% trans "No" %}
                  </a>
                  {% endif %}
                </div>

                </div>                
                <div class="clear"></div>                 

            </form>
        </div>
    </div>
{% endblock %}

apps/common/templates/generic_detail_subtemplate.html
{% load i18n %}

{% block stylesheets %}
    <style type="text/css">
        #subform form  textarea, 
        #subform form  select option,
        #subform form  input, 
        #subform form  select, 
        #subform form  input { background: none; color: black; border: none; }
    </style>
{% endblock %}

{% block content %}

    {% if form %}
        {% with "true" as read_only %}
            <div class="generic_subform">
                {% include "generic_form_subtemplate.html" %}
            </div><!--end generic_subform-->
        {% endwith %}
    {% endif %}
{% endblock %}

apps/common/templates/generic_form.html
{% extends "base.html" %}
{% load subtemplates_tags %}

{% block title %} :: {% with "true" as striptags %}{% include "calculate_form_title.html" %}{% endwith %}{% endblock %}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates_list %}
        {% if subtemplate.form %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                <div class="generic_subform">
                    {{ rendered_subtemplate }}
                </div>
        {% else %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
            {{ rendered_subtemplate }}
        {% endif %}
            {% if subtemplate.grid_clear or not subtemplate.grid %}
            {% endif %}
    {% endfor %}
{% endblock %}

{% block content %}
    {% if form %}
        <div class="generic_subform">
            {% include "generic_form_subtemplate.html" %}
        </div>
    {% endif %}
                             
<div class="container_12">
    {% for subtemplate in subtemplates_list %}
        <div class="grid_{{ subtemplate.grid|default:12 }}">       
            {% if subtemplate.form %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
            {% else %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {{ rendered_subtemplate }}
            {% endif %}
        </div>
        {% if subtemplate.grid_clear or not subtemplate.grid %}
            <div class="clear"></div> 
        {% endif %}
     {% endfor %}
</div>
{% endblock %}

apps/common/templates/generic_form_instance.html
{% load i18n %}
{% load styling %}

{{ form.media|safe }}  
{% add_classes_to_form form %}

{% if form.non_field_errors %}
    <div class="flash">
        {% for value in form.non_field_errors %}
            <div class="message error">
                <p>{{ value }}</p>
            </div>
      {% endfor %}                    
  </div>
{% endif %}

{% if form_display_mode_table %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    <tr class="{% cycle 'odd' 'even2' %}">
    {% for field in form.visible_fields %}
            <td title="{% if field.errors %}{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}{% else %}{{ field.help_text }}{% endif %}">
            {% if field.errors %}<div class="flash"><div class="error">{% endif %}
              {{ field }}
            {% if field.errors %}</div></div>{% endif %}
            </td>
    {% endfor %} 
    </tr>
{% else %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    
    {% for field in form.visible_fields %}
        <div class="group">
            {% if field.errors %}<div class="fieldWithErrors">{% endif %}
            <label class="label">{{ field.label_tag }}{% if field.field.required and not read_only and not form_hide_required_text %} ({% trans "required" %}){% endif %}</label>
            {% if field.errors %}<span class="error">{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}</span></div>{% endif %} 
            {{ field }}
            {% if field.help_text %}<span class="description">{{ field.help_text }}</span>{% endif %}
        </div>
    {% endfor %} 
{% endif %}

apps/common/templates/generic_form_subtemplate.html
{% load i18n %}
{% load default_icons %}
{% default_icons %}
                
{% if side_bar %}
    <div class="block">
    <h3>
{% else %}
    <div class="content">    
    <h2 class="title">
{% endif %}

{% include "calculate_form_title.html" %}

{% if side_bar %}
    </h3>
    <div class="content">
        <p>
{% else %}
    </h2>
    <div class="inner">
{% endif %}
    {% if form.is_multipart %}
        <form name="{{ form.prefix }}" enctype="multipart/form-data" method="{{ submit_method|default:'post' }}" action="{{ form_action }}" class="form">
    {% else %}
        <form name="{{ form.prefix }}" method="{{ submit_method|default:'post' }}" action="{{ form_action }}" class="form">
    {% endif %}
        {% if step_field %}
            <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
        {% endif %}
        
        {% if submit_method != "GET" and submit_method != "get" %}
            {% csrf_token %}
        {% endif %}
        
        {% if next %}
            <input name="next" type="hidden" value="{{ next }}" />
        {% endif %}          

        {% if previous %}
            <input name="previous" type="hidden" value="{{ previous }}" />
        {% endif %}

        {% for hidden_field in hidden_fields %}
           {{ hidden_field.as_hidden }}
        {% endfor %}
                   
        {% if form.management_form %}
            {% with form as formset %}
                {{ formset.management_form }}

                {% if form_display_mode_table %}
                    <table class="table">
                        <tbody>
                        <tr>
                            {% for field in formset.forms.0.visible_fields %}
                                <th>
                                    {{ field.label_tag }}{% if field.field.required and not read_only %} ({% trans "required" %}){% endif %}
                                </th>
                            {#{% if field.help_text %}<span class="description">{{ field.help_text }}</span>{% endif %}#}
                            {% endfor %} 
                        </tr>
                {% endif %}
                
                {% for form in formset.forms %}
                    {% include "generic_form_instance.html" %}
                {% endfor %}
                {% if form_display_mode_table %}
                    </tbody>
                    </table>
                {% endif %}
            {% endwith %}
        {% else %}
            {% include "generic_form_instance.html" %}
        {% endif %}
        {% if not read_only %}
        <div class="group navform wat-cf">
            <button class="button" type="submit" name="{% if form.prefix %}{{ form.prefix }}-submit{% else %}submit{% endif %}">
                {% if submit_icon %}
                    {{ submit_icon.display_small }}
                {% else %}
                    {{ icon_submit_default.display_small }}
                {% endif %}

                {% if submit_label %}{{ submit_label }}{% else %}{% if object %}{% trans "Save" %}{% else %}{% trans "Submit" %}{% endif %}{% endif %}
            </button>

              {% if previous %}
                  <a href="#header" onclick='{% if previous %}window.location.replace("{{ previous }}");{% else %}history.go(-1);{% endif %}' class="button">
                    {% if cancel_icon %}
                        {{ cancel_icon.display_small }}
                    {% else %}
                        {{ icon_cancel_default.display_small }}
                    {% endif %}
                      
                    {% if cancel_label %}{{ cancel_label }}{% else %}{% trans "Cancel" %}{% endif %}
                  </a>
              {% endif %}
        </div>
        {% endif %}
    </form>
    {% if side_bar %}
        </p></div><!--end content--></div><!--end block-->
    {% else %}
        </div></div>
    {% endif %}

apps/common/templates/generic_list_horizontal.html
{% extends "base.html" %}
{% load i18n %}
{% load navigation_tags %}
{% load subtemplates_tags %}

{% block title %} :: {% blocktrans with title|striptags as stripped_title %}List of {{ stripped_title }}{% endblocktrans %}{% endblock %}
{#{% block secondary_links %}{{ secondary_links|safe }}{% endblock %}#}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates_list %}
        {% if subtemplate.form %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                <div class="generic_subform">
                    {{ rendered_subtemplate }}
                </div>
        {% else %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
            {{ rendered_subtemplate }}
        {% endif %}
     {% endfor %}

{% endblock %}

{% block content %}
    {% include "generic_list_horizontal_subtemplate.html" %}

{% endblock %}

apps/common/templates/generic_subtemplate.html
{% if side_bar %}
    <div class="block">
        <h3>{{ title|capfirst }}</h3>
        <div class="content">
{% else %}
    <div class="content">    
        <h2 class="title">{{ title|capfirst }}</h2>
        <div class="inner">
{% endif %}

{% if content %}
    <p>{{ content|safe }}</p>
{% endif %}

{% for paragraph in paragraphs %}
    <p>{{ paragraph|safe }}</p>
{% endfor %}

</div></div>

apps/common/templates/generic_template.html
{% extends "base.html" %}
{% block title %} :: {{ title|capfirst }}{% endblock %}

{% block content %}
    {% include "generic_subtemplate.html" %}
{% endblock %}